### ISSUE TITLE
Error when running migrations on Mac

### ISSUE THREAD

**Issue by wolejnr** [pyung/pyconng#6]
In step 8 of the documentation for setting up the development environment, I get an
> ImportError: No module named 'django.urls'
This is after setting up the environment variable to map the database configuration and then running
`python manage.py migrate`

**Comment by danidee10** [comment]
Which version of django are you running?

On 15 Dec 2017 16:59, "Adewole Adewumi" <notifications@github.com> wrote:

In step 8 of the documentation for setting up the development environment,
I get an

ImportError: No module named 'django.urls'
This is after setting up the environment variable to map the database
configuration and then running
python manage.py migrate

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pyung/pyconng/issues/6>, or mute the thread

**Comment by wolejnr** [comment]
It is django 1.9.9

**Comment by gbozee** [comment]
what version of django was specified in the `requirements/base.txt`?

**Comment by gbozee** [comment]
You could also try upgrading django to 1.10 and see it it solves the issue. If it does, don't forget to update the dependencies in `requirements/base.txt`

**Comment by danidee10** [comment]
Yeah I believe that should solve the issue cuz prior to 1.10 it was
django.core.urlresolvers

**Comment by wolejnr** [comment]
I have upgraded to `Django 1.11.8` but I now get this error when I run `python manage.py migrate`
>TypeError: __init__() missing 1 required positional argument: 'settings_module'

The specific location is:
>File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/easy_thumbnails/conf.py", line 21, in __init__
    super(AppSettings, self).__init__(*args, **kwargs)

**Comment by gbozee** [comment]
Could u paste d full stack trace?

**Comment by wolejnr** [comment]
`(venv) Adewoles-MacBook-Air:pycon adewoleadewumi$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/easy_thumbnails/models.py", line 6, in <module>
    from easy_thumbnails import utils, signal_handlers
  File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/easy_thumbnails/utils.py", line 15, in <module>
    from easy_thumbnails.conf import settings
  File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/easy_thumbnails/conf.py", line 334, in <module>
    settings = Settings()
  File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/easy_thumbnails/conf.py", line 21, in __init__
    super(AppSettings, self).__init__(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'settings_module'`

**Comment by gbozee** [comment]
try installing `easy-thumbnails==2.4.2`

**Comment by gbozee** [comment]
don't forget to update the requirement for the particular package.

**Comment by wolejnr** [comment]
I installed `easy-thumbnails==2.4.2` and now it gives the following error when I run `python manage.py migrate`

>(venv) Adewoles-MacBook-Air:pycon adewoleadewumi$ export DATABASE_URL=postgres://postgres:postgres@localhost:5432/pyconng
(venv) Adewoles-MacBook-Air:pycon adewoleadewumi$ export DJANGO_SETTINGS_MODULE=config.settings.local
(venv) Adewoles-MacBook-Air:pycon adewoleadewumi$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/symposion/conference/models.py", line 6, in <module>
    from timezone_field import TimeZoneField
  File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/timezone_field/__init__.py", line 4, in <module>
    from timezone_field.fields import TimeZoneField
  File "/Users/adewoleadewumi/Documents/python_codes/Development/pycon/venv/lib/python3.5/site-packages/timezone_field/fields.py", line 111, in <module>
    class TimeZoneField(six.with_metaclass(models.SubfieldBase,
AttributeError: module 'django.db.models' has no attribute 'SubfieldBase'

**Comment by gbozee** [comment]
The problem is no longer from easy_thumbnails . its another dependency called timezone that is causing this error

**Comment by gbozee** [comment]
I just updated the dependencies in the `base.txt` on  the `archive/2017` branch 

You can take a look with this diff 577fa3ab96366abed8ca990746340099c16dc152

**Comment by wolejnr** [comment]
Many thanks @gbozee it finally worked.
